INSERT INTO Cards (color, number, image, name) VALUES ("0red", 1, "/assets/images/nintendo/N1.png", "Mario");
INSERT INTO Cards (color, number, image, name) VALUES ("0red", 2, "/assets/images/nintendo/N2.png", "Luigi");
INSERT INTO Cards (color, number, image, name) VALUES ("0red", 3, "/assets/images/nintendo/N3.png", "Peach");
INSERT INTO Cards (color, number, image, name) VALUES ("0red", 4, "/assets/images/nintendo/N4.png", "Piranha Plant");
INSERT INTO Cards (color, number, image, name) VALUES ("0red", 5, "/assets/images/nintendo/N5.png", "Rosalina");
INSERT INTO Cards (color, number, image, name) VALUES ("0red", 6, "/assets/images/nintendo/N6.png", "Shy Guy");
INSERT INTO Cards (color, number, image, name) VALUES ("0red", 7, "/assets/images/nintendo/N7.png", "King Boo");
INSERT INTO Cards (color, number, image, name) VALUES ("0red", 8, "/assets/images/nintendo/N8.png", "Magikoopa");
INSERT INTO Cards (color, number, image, name) VALUES ("0red", 9, "/assets/images/nintendo/N9.png", "Goomba");
INSERT INTO Cards (color, number, image, name) VALUES ("0red", 10, "/assets/images/nintendo/N10.png", "Toad");
INSERT INTO Cards (color, number, image, name) VALUES ("0red", 11, "/assets/images/nintendo/N11.png", "Donkey Kong");
INSERT INTO Cards (color, number, image, name) VALUES ("0red", 12, "/assets/images/nintendo/N12.png", "Wario");
INSERT INTO Cards (color, number, image, name) VALUES ("0red", 13, "/assets/images/nintendo/N13.png", "Bowser");
INSERT INTO Cards (color, number, image, name) VALUES ("1grey", 1, "/assets/images/disney/d1.png", "Genie");
INSERT INTO Cards (color, number, image, name) VALUES ("1grey", 2, "/assets/images/disney/d2.png", "Jaffar");
INSERT INTO Cards (color, number, image, name) VALUES ("1grey", 3, "/assets/images/disney/d3.png", "Captain Hook");
INSERT INTO Cards (color, number, image, name) VALUES ("1grey", 4, "/assets/images/disney/d4.png", "Boo");
INSERT INTO Cards (color, number, image, name) VALUES ("1grey", 5, "/assets/images/disney/d5.png", "Nemo");
INSERT INTO Cards (color, number, image, name) VALUES ("1grey", 6, "/assets/images/disney/d6.png", "Peter Pan");
INSERT INTO Cards (color, number, image, name) VALUES ("1grey", 7, "/assets/images/disney/d7.png", "Simba");
INSERT INTO Cards (color, number, image, name) VALUES ("1grey", 8, "/assets/images/disney/d8.png", "Tick-Tock");
INSERT INTO Cards (color, number, image, name) VALUES ("1grey", 9, "/assets/images/disney/d9.png", "Randall");
INSERT INTO Cards (color, number, image, name) VALUES ("1grey", 10, "/assets/images/disney/d10.png", "Rattigan");
INSERT INTO Cards (color, number, image, name) VALUES ("1grey", 11, "/assets/images/disney/d11.png", "Snow White");
INSERT INTO Cards (color, number, image, name) VALUES ("1grey", 12, "/assets/images/disney/d12.png", "Ursula");
INSERT INTO Cards (color, number, image, name) VALUES ("1grey", 13, "/assets/images/disney/d13.png", "Belle");
INSERT INTO Cards (color, number, image, name) VALUES ("2blue", 1, "/assets/images/pokemon/p1.png", "Absol");
INSERT INTO Cards (color, number, image, name) VALUES ("2blue", 2, "/assets/images/pokemon/p2.png", "Celebi");
INSERT INTO Cards (color, number, image, name) VALUES ("2blue", 3, "/assets/images/pokemon/p3.png", "Froakie");
INSERT INTO Cards (color, number, image, name) VALUES ("2blue", 4, "/assets/images/pokemon/p4.png", "Latias");
INSERT INTO Cards (color, number, image, name) VALUES ("2blue", 5, "/assets/images/pokemon/p5.png", "Lucario");
INSERT INTO Cards (color, number, image, name) VALUES ("2blue", 6, "/assets/images/pokemon/p6.png", "Pikachu");
INSERT INTO Cards (color, number, image, name) VALUES ("2blue", 7, "/assets/images/pokemon/p7.png", "Politoed");
INSERT INTO Cards (color, number, image, name) VALUES ("2blue", 8, "/assets/images/pokemon/p8.png", "Snorlax");
INSERT INTO Cards (color, number, image, name) VALUES ("2blue", 9, "/assets/images/pokemon/p9.png", "Spheal");
INSERT INTO Cards (color, number, image, name) VALUES ("2blue", 10, "/assets/images/pokemon/p10.png", "Vespiquen");
INSERT INTO Cards (color, number, image, name) VALUES ("2blue", 11, "/assets/images/pokemon/p11.png", "Volcarona");
INSERT INTO Cards (color, number, image, name) VALUES ("2blue", 12, "/assets/images/pokemon/p12.png", "Whimsicott");
INSERT INTO Cards (color, number, image, name) VALUES ("2blue", 13, "/assets/images/pokemon/p13.png", "Xerneas");
INSERT INTO Cards (color, number, image, name) VALUES ("3brown", 1, "/assets/images/lastAirbender/la1.png", "Cabbage Man");
INSERT INTO Cards (color, number, image, name) VALUES ("3brown", 2, "/assets/images/lastAirbender/la2.png", "Aang");
INSERT INTO Cards (color, number, image, name) VALUES ("3brown", 3, "/assets/images/lastAirbender/la3.png", "Appa");
INSERT INTO Cards (color, number, image, name) VALUES ("3brown", 4, "/assets/images/lastAirbender/la4.png", "Azula");
INSERT INTO Cards (color, number, image, name) VALUES ("3brown", 5, "/assets/images/lastAirbender/la5.png", "Iroh");
INSERT INTO Cards (color, number, image, name) VALUES ("3brown", 6, "/assets/images/lastAirbender/la6.png", "Katara");
INSERT INTO Cards (color, number, image, name) VALUES ("3brown", 7, "/assets/images/lastAirbender/la7.png", "Momo");
INSERT INTO Cards (color, number, image, name) VALUES ("3brown", 8, "/assets/images/lastAirbender/la8.png", "Ozai");
INSERT INTO Cards (color, number, image, name) VALUES ("3brown", 9, "/assets/images/lastAirbender/la9.png", "Sokka");
INSERT INTO Cards (color, number, image, name) VALUES ("3brown", 10, "/assets/images/lastAirbender/la10.png", "Suki");
INSERT INTO Cards (color, number, image, name) VALUES ("3brown", 11, "/assets/images/lastAirbender/la11.png", "Mai & Ty Lee");
INSERT INTO Cards (color, number, image, name) VALUES ("3brown", 12, "/assets/images/lastAirbender/la12.png", "Toph");
INSERT INTO Cards (color, number, image, name) VALUES ("3brown", 13, "/assets/images/lastAirbender/la13.png", "Zuko");
INSERT INTO Cards (color, number, image, name) VALUES ("4green", 1, "/assets/images/rick&morty/rm1.png", "Beth");
INSERT INTO Cards (color, number, image, name) VALUES ("4green", 2, "/assets/images/rick&morty/rm2.png", "Birdperson");
INSERT INTO Cards (color, number, image, name) VALUES ("4green", 3, "/assets/images/rick&morty/rm3.png", "Fart");
INSERT INTO Cards (color, number, image, name) VALUES ("4green", 4, "/assets/images/rick&morty/rm4.png", "Cromulon");
INSERT INTO Cards (color, number, image, name) VALUES ("4green", 5, "/assets/images/rick&morty/rm5.png", "Jerry");
INSERT INTO Cards (color, number, image, name) VALUES ("4green", 6, "/assets/images/rick&morty/rm6.png", "Morty");
INSERT INTO Cards (color, number, image, name) VALUES ("4green", 7, "/assets/images/rick&morty/rm7.png", "Mr. Meeseeks");
INSERT INTO Cards (color, number, image, name) VALUES ("4green", 8, "/assets/images/rick&morty/rm8.png", "Mr. Poopy Butthole");
INSERT INTO Cards (color, number, image, name) VALUES ("4green", 9, "/assets/images/rick&morty/rm9.png", "Pickle Rick");
INSERT INTO Cards (color, number, image, name) VALUES ("4green", 10, "/assets/images/rick&morty/rm10.png", "Rick");
INSERT INTO Cards (color, number, image, name) VALUES ("4green", 11, "/assets/images/rick&morty/rm11.png", "Squanchy");
INSERT INTO Cards (color, number, image, name) VALUES ("4green", 12, "/assets/images/rick&morty/rm12.png", "Summer");
INSERT INTO Cards (color, number, image, name) VALUES ("4green", 13, "/assets/images/rick&morty/rm13.png", "Tiny Rick");
INSERT INTO Cards (color, number, image, name) VALUES ("5orange", 1, "/assets/images/adventureTime/at1.png", "Bmo");
INSERT INTO Cards (color, number, image, name) VALUES ("5orange", 2, "/assets/images/adventureTime/at2.png", "Flame Princess");
INSERT INTO Cards (color, number, image, name) VALUES ("5orange", 3, "/assets/images/adventureTime/at3.png", "Grob Gob Glob Grod");
INSERT INTO Cards (color, number, image, name) VALUES ("5orange", 4, "/assets/images/adventureTime/at4.png", "Gunter");
INSERT INTO Cards (color, number, image, name) VALUES ("5orange", 5, "/assets/images/adventureTime/at5.png", "Ice King");
INSERT INTO Cards (color, number, image, name) VALUES ("5orange", 6, "/assets/images/adventureTime/at6.png", "Jake");
INSERT INTO Cards (color, number, image, name) VALUES ("5orange", 7, "/assets/images/adventureTime/at7.png", "Lemongrab");
INSERT INTO Cards (color, number, image, name) VALUES ("5orange", 8, "/assets/images/adventureTime/at8.png", "The Lich");
INSERT INTO Cards (color, number, image, name) VALUES ("5orange", 9, "/assets/images/adventureTime/at9.png", "Lumpy Space Princess");
INSERT INTO Cards (color, number, image, name) VALUES ("5orange", 10, "/assets/images/adventureTime/at10.png", "Magic Man");
INSERT INTO Cards (color, number, image, name) VALUES ("5orange", 11, "/assets/images/adventureTime/at11.png", "Marceline");
INSERT INTO Cards (color, number, image, name) VALUES ("5orange", 12, "/assets/images/adventureTime/at12.png", "Princess Bubblegum");
INSERT INTO Cards (color, number, image, name) VALUES ("5orange", 13, "/assets/images/adventureTime/at13.png", "Finn");
INSERT INTO Cards (color, number, image, name) VALUES ("6yellow", 1, "/assets/images/league/l1.png", "Warwick");
INSERT INTO Cards (color, number, image, name) VALUES ("6yellow", 2, "/assets/images/league/l2.png", "Elise");
INSERT INTO Cards (color, number, image, name) VALUES ("6yellow", 3, "/assets/images/league/l3.png", "Ekko");
INSERT INTO Cards (color, number, image, name) VALUES ("6yellow", 4, "/assets/images/league/l4.png", "Ashe");
INSERT INTO Cards (color, number, image, name) VALUES ("6yellow", 5, "/assets/images/league/l5.png", "Lucian");
INSERT INTO Cards (color, number, image, name) VALUES ("6yellow", 6, "/assets/images/league/l6.png", "Nocturne");
INSERT INTO Cards (color, number, image, name) VALUES ("6yellow", 7, "/assets/images/league/l7.png", "Ezreal");
INSERT INTO Cards (color, number, image, name) VALUES ("6yellow", 8, "/assets/images/league/l8.png", "Diana");
INSERT INTO Cards (color, number, image, name) VALUES ("6yellow", 9, "/assets/images/league/l9.png", "Poppy");
INSERT INTO Cards (color, number, image, name) VALUES ("6yellow", 10, "/assets/images/league/l10.png", "Shyvana");
INSERT INTO Cards (color, number, image, name) VALUES ("6yellow", 11, "/assets/images/league/l11.png", "Rengar");
INSERT INTO Cards (color, number, image, name) VALUES ("6yellow", 12, "/assets/images/league/l12.png", "Wukong");
INSERT INTO Cards (color, number, image, name) VALUES ("6yellow", 13, "/assets/images/league/l13.png", "Katarina");
INSERT INTO Cards (color, number, image, name) VALUES ("7purple", 1, "/assets/images/fireEmblem/fe1.png", "Miriel");
INSERT INTO Cards (color, number, image, name) VALUES ("7purple", 2, "/assets/images/fireEmblem/fe2.png", "Tiki");
INSERT INTO Cards (color, number, image, name) VALUES ("7purple", 3, "/assets/images/fireEmblem/fe3.png", "Cherche");
INSERT INTO Cards (color, number, image, name) VALUES ("7purple", 4, "/assets/images/fireEmblem/fe4.png", "Chrom");
INSERT INTO Cards (color, number, image, name) VALUES ("7purple", 5, "/assets/images/fireEmblem/fe5.png", "Gaius");
INSERT INTO Cards (color, number, image, name) VALUES ("7purple", 6, "/assets/images/fireEmblem/fe6.png", "Olivia");
INSERT INTO Cards (color, number, image, name) VALUES ("7purple", 7, "/assets/images/fireEmblem/fe7.png", "Lon'qu");
INSERT INTO Cards (color, number, image, name) VALUES ("7purple", 8, "/assets/images/fireEmblem/fe8.png", "Lucina");
INSERT INTO Cards (color, number, image, name) VALUES ("7purple", 9, "/assets/images/fireEmblem/fe9.png", "Say'ri");
INSERT INTO Cards (color, number, image, name) VALUES ("7purple", 10, "/assets/images/fireEmblem/fe10.png", "Sumia");
INSERT INTO Cards (color, number, image, name) VALUES ("7purple", 11, "/assets/images/fireEmblem/fe11.png", "Vaike");
INSERT INTO Cards (color, number, image, name) VALUES ("7purple", 12, "/assets/images/fireEmblem/fe12.png", "Henry");
INSERT INTO Cards (color, number, image, name) VALUES ("7purple", 13, "/assets/images/fireEmblem/fe13.png", "Virion");